export const DESIGN_TOKENS = {
  name: "Emerald Premium Productivity",
  colors: {
    surface: {
      DEFAULT: "#f8f9ff",
      dim: "#cbdbf5",
      bright: "#f8f9ff",
      lowest: "#ffffff",
      low: "#eff4ff",
      container: "#e5eeff",
      high: "#dce9ff",
      highest: "#d3e4fe",
      variant: "#d3e4fe",
    },
    onSurface: "#0b1c30",
    onSurfaceVariant: "#3c4a42",
    inverseSurface: "#213145",
    inverseOnSurface: "#eaf1ff",
    outline: "#6c7a71",
    outlineVariant: "#bbcabf",
    surfaceTint: "#006c49",
    primary: {
      DEFAULT: "#006c49",
      on: "#ffffff",
      container: "#10b981",
      onContainer: "#00422b",
      inverse: "#4edea3",
    },
    secondary: {
      DEFAULT: "#2b6954",
      on: "#ffffff",
      container: "#adedd3",
      onContainer: "#306d58",
    },
    tertiary: {
      DEFAULT: "#55615a",
      on: "#ffffff",
      container: "#99a69e",
      onContainer: "#303c36",
    },
    error: {
      DEFAULT: "#ba1a1a",
      on: "#ffffff",
      container: "#ffdad6",
      onContainer: "#93000a",
    },
    primaryFixed: "#6ffbbe",
    primaryFixedDim: "#4edea3",
    onPrimaryFixed: "#002113",
    onPrimaryFixedVariant: "#005236",
    secondaryFixed: "#b0f0d6",
    secondaryFixedDim: "#95d3ba",
    onSecondaryFixed: "#002117",
    onSecondaryFixedVariant: "#0b513d",
    tertiaryFixed: "#d9e6dd",
    tertiaryFixedDim: "#bdcac1",
    onTertiaryFixed: "#131e19",
    onTertiaryFixedVariant: "#3e4943",
    background: "#f8f9ff",
    onBackground: "#0b1c30",
  },
  typography: {
    fontFamily: {
      // Single, consistent modern Arabic font used across the entire application.
      sans: "'IBM Plex Sans Arabic', 'Hanken Grotesk', system-ui, sans-serif",
      display: "'IBM Plex Sans Arabic', 'Hanken Grotesk', system-ui, sans-serif",
      mono: "'IBM Plex Sans Arabic', 'Hanken Grotesk', system-ui, sans-serif",
    },
    displayLg: {
      fontSize: "48px",
      fontWeight: "700",
      lineHeight: "56px",
      letterSpacing: "-0.02em",
    },
    headlineLg: {
      fontSize: "32px",
      fontWeight: "600",
      lineHeight: "40px",
      letterSpacing: "-0.01em",
    },
    headlineLgMobile: {
      fontSize: "24px",
      fontWeight: "600",
      lineHeight: "32px",
    },
    titleMd: {
      fontSize: "20px",
      fontWeight: "600",
      lineHeight: "28px",
    },
    bodyLg: {
      fontSize: "16px",
      fontWeight: "400",
      lineHeight: "24px",
    },
    bodySm: {
      fontSize: "14px",
      fontWeight: "400",
      lineHeight: "20px",
    },
    labelMd: {
      fontSize: "12px",
      fontWeight: "600",
      lineHeight: "16px",
      letterSpacing: "0.05em",
    },
  },
  radii: {
    sm: "0.25rem",
    DEFAULT: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    full: "9999px",
  },
  spacing: {
    sidebarExpanded: "256px",
    sidebarCollapsed: "80px",
    gutter: "24px",
    marginPage: "32px",
    stackSm: "8px",
    stackMd: "16px",
  },
} as const;
